version: 2.1

references:
  default_docker_ruby_executor: &default_docker_ruby_executor
    image: circleci/ruby:2.7.0
    environment:
      BUNDLE_JOBS: 3
      BUNDLE_RETRY: 3
      BUNDLE_PATH: vendor/bundle
      APP_ENV: test

orbs:
  ruby-linter: amyroi/ruby-linter@1.0.0

jobs:
  build:
    docker:
      - *default_docker_ruby_executor
    working_directory: ~/profile_app
    steps:
      - checkout
      - run: bundle check || bundle install

  rspec:
    docker:
      - *default_docker_ruby_executor
    working_directory: ~/profile_app
    steps:
      - checkout
      - run: bundle check || bundle install
      - run: mkdir /tmp/rspec
      - run:
          command: bundle exec rspec --format progress --format RspecJunitFormatter -o /tmp/rspec/rspec.xml
          when: always
      - store_test_results:
          path: /tmp/rspec

  rubocop:
    docker:
      - *default_docker_ruby_executor
    working_directory: ~/profile_app
    steps:
      - checkout
      - run: bundle check || bundle install
      - run: mkdir /tmp/rubocop
      - ruby-linter/rubocop:
          files: /*.rb lib/**/*.rb config/**/*.rb spec/**/*.rb
          report_dir: /tmp/rubocop

  deploy:
    machine:
      enabled: true
    working_directory: ~/profile_app
    environment:
      HEROKU_APP: ""
    steps:
      - checkout
      - run: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP.git master

workflows:
  version: 2.1
  build_test_deploy:
    jobs:
      - build
      - rspec:
          requires:
            - build
      - rubocop:
          requires:
            - build
      - deploy:
          requires:
            - rspec
            - rubocop
          filters:
            branches:
              only: master
